name: prime_tect_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.3
  syncfusion_flutter_pdfviewer: ^20.4.53
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pdf/

